EVENT_CATEGORIES = \
    {
        1: 'music',
        2: 'conference',
        3: 'comedy',
        4: 'learning_education',
        5: 'family_fun_kids',
        6: 'festivals_parades',
        7: 'movies_film',
        8: 'food',
        9: 'fundraisers',
        10: 'art',
        11: 'support',
        12: 'holiday',
        13: 'books',
        14: 'attractions',
        15: 'community',
        16: 'business',
        17: 'singles_social',
        18: 'schools_alumni',
        19: 'clubs_associations',
        20: 'outdoors_recreation',
        21: 'performing_arts',
        22: 'animals',
        23: 'politics_activism',
        24: 'sales',
        25: 'science',
        26: 'religion_spirituality',
        27: 'sports',
        28: 'technology',
        29: 'other'
    }
